In [6]:
#  Numpy is just a special type of array in python
# create a basic python array
list1 = [1,2,3,4,5]
# you could do something about it , for example print the list
print(list1)
# or print first element
print(list1[0])

[1, 2, 3, 4, 5]
1


In [7]:
# but we can run into some problems using list for large set of data,it's a problem when you start using  massive amounts of data.
# and machine learning is all about using massive amounts of data. It is a lot slower.
# instead of using a list for data science and machine learning, we use something call a numpy array


import numpy as np # type: ignore

# ndarray = n-dimensional array, different dimension in array , 3 / 4 / 100 dimension
# because we import as np , so we could call it np here 
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
# numpy list just a list , but more powerful
print(np1)

print(np1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [8]:
# we could create np in a quick way, and we get the some thing
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# step from 0 to 10 , the step is 2
np3 = np.arange(0, 10 , 2)
print(np3)

[0 2 4 6 8]


In [11]:
# Zero
np4 = np.zeros(10)
# There are 10 zero 0. , because they are not strictly an integer
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# Multidimensional zeros
np5 = np.zeros((2, 10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
# Full
np6 = np.full((10), 6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [15]:
# Multidimensional Full
np7 = np.full((2,10), 6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [17]:
# Convert Python lists to np
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[0])

[1 2 3 4 5]
1
